### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by jclerc** [foobuzz/statify#4]
hi @foobuzz 

i kinda love you but ive got a lot of issues while running ✨ statify ✨

a cron is running every other hour but sometimes fails due to a classical timeout, so what about increasing it a bit?

i didnt bother looking into how to do that in spotipy but please do it as soon as possible thx

```
Traceback (most recent call last):
  File "/home/pi/.local/bin/statify", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/statify/statify.py", line 36, in main
    code = _main(args)
  File "/home/pi/.local/lib/python3.7/site-packages/statify/statify.py", line 100, in _main
    pull_playlists(spotify, database)
  File "/home/pi/.local/lib/python3.7/site-packages/statify/statify.py", line 171, in pull_playlists
    spotify_tracks = list(spotify.playlist_tracks(playlist_obj.spotify_id))
  File "/home/pi/.local/lib/python3.7/site-packages/statify/spotify_client.py", line 125, in playlist_tracks
    page_size=100,  # Max allowed
  File "/home/pi/.local/lib/python3.7/site-packages/statify/spotify_client.py", line 80, in _paginate_spotipy_method
    **kwargs,
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 634, in playlist_tracks
    market, additional_types)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 663, in playlist_items
    additional_types=",".join(additional_types)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 284, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 241, in _internal_call
    timeout=self.requests_timeout, **args
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)
```

**Comment by foobuzz** [comment]
Hey Jonathan,

Thanks for your interest for Statify! :relaxed: In fact I've recently specialized in dealing with HTTP errors, so I knew I would be up to the task :muscle:  But as your noticed this matter can already be dealt with by the underlying Spotipy client, so I was able to spin up some Sublime Merge and commit the necessary changes. 

This is now available on Statify 1.2.0, so you can simply upgrade to this version and append the following to your `~/.config/statify.yaml`:

```yaml
client_args:
  requests_timeout: 30  # or whatever value suits you
```

Don't hesitate if you have any question :)
