### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by jclerc** [foobuzz/statify#7]
please help!!! this is my favorite tool and it doesn't work anymore

```
$ statify pull
^C^CTraceback (most recent call last):
  File "/home/pi/.local/bin/statify", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/statify/statify.py", line 36, in main
    code = _main(args)
  File "/home/pi/.local/lib/python3.7/site-packages/statify/statify.py", line 101, in _main
    pull_playlists(spotify, database)
  File "/home/pi/.local/lib/python3.7/site-packages/statify/statify.py", line 172, in pull_playlists
    spotify_tracks = list(spotify.playlist_tracks(playlist_obj.spotify_id))
  File "/home/pi/.local/lib/python3.7/site-packages/statify/spotify_client.py", line 126, in playlist_tracks
    page_size=100,  # Max allowed
  File "/home/pi/.local/lib/python3.7/site-packages/statify/spotify_client.py", line 81, in _paginate_spotipy_method
    **kwargs,
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 634, in playlist_tracks
    market, additional_types)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 663, in playlist_items
    additional_types=",".join(additional_types)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 284, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 241, in _internal_call
    timeout=self.requests_timeout, **args
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 723, in urlopen
    retries.sleep(response)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 277, in sleep
    slept = self.sleep_for_retry(response)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 256, in sleep_for_retry
    time.sleep(retry_after)
KeyboardInterrupt
```

**Comment by foobuzz** [comment]
Hello! ![nice](https://github.com/foobuzz/statify/assets/12711665/8949fa82-2579-4987-986f-b04cef06d096)


What was the problem exactly before issuing the keyboard interrupt?

**Comment by jclerc** [comment]
it waits forever & ever

**Comment by jclerc** [comment]
like our love

**Comment by jclerc** [comment]
it never ends
